### ISSUE TITLE
Fortran runtime error

### ISSUE THREAD

**Issue by tstone-1** [richardjgowers/poreblazer#1]
Hi,

when trying to compile the source using make (gfortran compiler/Ubuntu 18.04), poreblazer.exe is created. However, when trying to run poreblazer.exe on an input file, the program will terminate in error:

~/poreblazer-master/HKUST1$ ./poreblazer.exe < input.dat
 !-------------------------------------------------------!
 ! Welcome to Poreblazer_v3.0.5/Linux/Windows XP         !
 ! Developed by: Lev Sarkisov, 2012/18                   !
 ! Cite: Sarkisov, Harrison, Molecular Simulation, 2011  !
 !-------------------------------------------------------!

 Step 1/8
 !-------------------------------------------------------!
 ! Proceed with initialization and data input            !
 !-------------------------------------------------------!

At line 358 of file poreblazer.f90 (unit = 3, file = 'defaults.dat')
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0  0x7f818650831a
#1  0x7f8186508ec5
#2  0x7f818650968d
#3  0x7f8186675924
#4  0x7f8186678c1a
#5  0x7f818667a0f9
#6  0x55d07e41cc22
#7  0x55d07e41da9d
#8  0x55d07e4035ae
#9  0x7f8185d7fb96
#10  0x55d07e4035e9
#11  0xffffffffffffffff
~/poreblazer-master/HKUST1$ 

Any suggestions on that? Thanks & Best Regards.

**Comment by richardjgowers** [comment]
Hi @tstone-1 , I've not used poreblazer in a while, so I can't really help.  If I had to guess, there's probably something wrong with the input file, it looks like it can't read it. Your best bet would be to email Prof. Lev Sarkisov [here](http://www.homepages.ed.ac.uk/lsarkiso/Contact.html)
